### ISSUE TITLE
Accounts - Test a user's profile

### ISSUE THREAD

**Issue by m1yag1** [openstax/os-automation#71] opened 2018-07-12 15:03 UTC
@m1yag1 commented on [Thu Jul 12 2018](https://github.com/openstax/quality-assurance-meta/issues/50)

# CASE NUM: C195545
## Section

Accounts > Profile

## User story

AAT, I'd like an automated test that asserts Test a user's profile

## Preconditions

1. a valid student login and password

## Steps

1. Log into Accounts as the student

## Expected Result

1. The admin console links are not displayed
2. The user's name, username (if assigned), e-mails and log in methods are shown

---

@m1yag1 commented on [Thu Jul 12 2018](https://github.com/openstax/quality-assurance-meta/issues/50#issuecomment-404544030)

Issue moved to [openstax/os-automation #70](https://github.com/openstax/os-automation/issues/70) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gregfitch** [comment] 2018-07-17 21:59
Duplicate of #70

**Closed by gregfitch** 2018-07-17 21:59 UTC
